---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: "{{user}}"

  tasks:
    - include: tasks/python.yaml
    - include: tasks/git.yaml
    - include: tasks/terminator.yaml
    - include: tasks/java-8.yaml
    - include: tasks/java-11.yaml
    - include: tasks/utils.yaml
    - include: tasks/chrome.yaml
    - include: tasks/vs-code.yaml
    - include: tasks/postman.yaml 
    - include: tasks/obs-studio.yaml
    - include: tasks/dbeaver.yaml
    - include: tasks/docker.yaml
    - include: tasks/dcr-compose.yaml
    - include: tasks/jetbrains-toolbox.yaml    
