---
- name: Check if Google Chrome apt already exists
  stat:
    path: /etc/apt/sources.list.d/google-chrome.list
  register: google_apt_exists
  ignore_errors: True

- name: Add Google Chrome key
  become_user: root
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: not google_apt_exists.stat.exists

- name: Add Google Chrome repo
  become_user: root
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest=/etc/apt/sources.list.d/google-chrome.list owner=root group=root mode=644
  when: not google_apt_exists.stat.exists

- name: Install Google Chrome
  become_user: root
  apt:
    name: google-chrome-stable
    state: latest
