---
- name: Download Docker-Compose
  become_user: root
  shell:  sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Apply executable permissions to the binary
  become_user: root
  shell: sudo chmod +x /usr/local/bin/docker-compose