---
- name: Install git
  tags:
    - packages
  become_user: root
  apt:
    name: git
    state: present
    
- name: Configure branch name in bashrc file
  tags:
    - configuration
  blockinfile: 
    path: ~/.bashrc
    insertafter: EOF
    marker: "#{mark} Git by Ansible"
    block: | 
      parse_git_branch() {
          git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }
      export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "
  
