---
- name: Download Jetbrains Toolbox tar
  shell: wget -q -O jetbrains-toolbox-1.21.9712.tar.gz https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.21.9712.tar.gz?_gl=1*wsw9yl*_ga*OTEzNzY3MTg5LjE2MTIwNDM4NTc.*_ga_V0XZL7QHEB*MTYzMzg4MzIzNy4yLjEuMTYzMzg4NDI5My4w&_ga=2.165010559.1110634093.1633879211-913767189.1612043857

- name: Check jetbrains-toolbox-1.21.9712.tar.gz
  shell: find jetbrains-toolbox-1.21.9712.tar.gz

- name: Move to work dir
  become_user: root
  shell: mv jetbrains-toolbox-1.21.9712.tar.gz ../../tools