---
- name: Download VS Code
  become_user: root
  shell: wget -q -O vscode_install.deb https://go.microsoft.com/fwlink/?LinkID=760868

- name: Check VS Code file name
  shell: find vscode_install.deb
  register: vs_code_file

- name: Install VS Code
  become_user: root
  shell: apt install ./{{ vs_code_file.stdout }}

- name: Install VS Code extensions
  command: code --install-extension {{ item }}
  with_items:
    - dbaeumer.vscode-eslint
    - hookyqr.beautify
    - eamodio.gitlens
    - pkief.material-icon-theme
    - ms-azuretools.vscode-docker
    - vscoss.vscode-ansible

- name: Remove VS Code file installation
  file:
    path: ./vscode_install.deb
    state: absent